Repository StackStorm/st2web, pull requests merged in 2022-10, with the labels that each got.

#990 Escape text in notifications + bump node version
  CHANGELOG.rst
  Dockerfile
  Dockerfile-dev
  Dockerfile-nginx
  Dockerfile-nginx-dev
  modules/st2-notification/notification.js
Labels: bug, enhancement

#963 Hotkey Shortcuts and Open in New Tab/Window
  CHANGELOG.rst
  apps/st2-workflows/workflows.component.js
  modules/st2flow-canvas/index.js
  modules/st2flow-palette/action.js
  modules/st2flow-palette/style.css
  tasks/lint.js
Labels: RFR

#992 Search Criteria Support in the Web UI - Updated
  CHANGELOG.rst
  apps/st2-rules/rules-details.component.js
  modules/st2-criteria/criteria.component.js
  modules/st2-criteria/style.css
  modules/st2-panel/panel.component.js
  modules/st2-panel/style.css
Labels: feature

#965 Auto-Save Changes in the Workflow Composer
  CHANGELOG.rst
  apps/st2-workflows/store.js
  apps/st2-workflows/workflows.component.js
  modules/st2flow-canvas/index.js
  modules/st2flow-details/index.js
  modules/st2flow-details/meta-panel.js
  modules/st2flow-details/style.css
  modules/st2flow-editor/index.js
Labels: feature
