Repository StackStorm/st2web, pull requests merged in 2023-10, with the labels that each got.

#1008 fix lerna version
  .circleci/config.yml
  CHANGELOG.rst
  Makefile
Labels: bug

#1009 Update dependencies
  CHANGELOG.rst
  modules/st2-api/api.js
  package.json
  tasks/serve.js
  yarn.lock
Labels: enhancement

#1010 Update Node version to current
  .circleci/config.yml
  CHANGELOG.rst
  Dockerfile
  Dockerfile-dev
  Dockerfile-nginx
  Dockerfile-nginx-dev
  README.md
  package.json
  yarn.lock
Labels: enhancement, security
